Long name support
philburk/pforth pull request #182
Opened 2024-12-27 12:13 UTC by robzed

This adds long word name support. 

Questions:
1. Currently this is gated by a #define `LONG_NAME_SUPPORT` - currently enabled, but it can be build without to support old dictionaries with a build - however, maybe we should remove this and only support long names?

2. I added two Primitive Token IDS - which expose the FLAG_SMUDGE and MASK_NAME_SIZE ... these allow the Forth files to not have magic numbers unrelated to the Forth core... I can understand why we didn't do this in the past (size), but I think the dependency is strong between the two - and the Forth code is clearer for it. However it is a design decision - so should we do this or revert this part? 

3. I left FLAG_PRECEDENCE commented out - maybe this should be removed. 

Name to long warnings/errors to be raised as a separate PR.

2024-12-31 22:17 UTC, philburk requested changes
This looks really good!
Let's keep it switchable. That will make it easier to debug if there is a name size
related problem.

2024-12-31 22:17 UTC, philburk commented on csrc/pf_guts.h
> +#define LONG_NAME_SUPPORT
Let's make this like the other compile time switches defined at:

https://www.softsynth.com/pforth/pf_ref.php#Compiler-Options

Let's rename it to PF_SUPPORT_LONG_NAMES
and leave it undefined for now.
Maybe we can test it on/off in GitHub Actions.

2024-12-31 22:17 UTC, philburk commented on csrc/pf_guts.h
> +/* #define FLAG_PRECEDENCE (0x80) */
Please add:
/* The IMMEDIATE flag is known as the "precedence bit" on some other Forth systems. */

2024-12-31 22:22 UTC, philburk commented on csrc/pf_guts.h
> + * for a word names.
I could also be convinced to just make long names the default. Hmm.

2025-01-01 14:14 UTC, robzed commented on csrc/pf_guts.h
> +/* #define FLAG_PRECEDENCE (0x80) */
Done

2025-01-01 14:14 UTC, robzed commented on csrc/pf_guts.h
> +#define LONG_NAME_SUPPORT
Done, please review. 
NOT enabled by default.

2025-01-01 14:14 UTC, robzed commented on csrc/pf_guts.h
> + * for a word names.
Done

2025-01-01 14:19 UTC, robzed commented
Please review latest changes. 
As mentioned before - overlong names will be warning/resolution on a separate PR. 
(This includes `LONGEST_WORD_NAME+9`, rather than +1,  since this requires more investigation.)

2025-01-02 01:35 UTC, philburk approved these changes
Thanks for doing this. Seeing the long name get silently truncated by the mask is scary.

2025-01-02 01:39 UTC, merged