fix warnings in WriteCellBigEndian() for 32bit builds
philburk/pforth pull request #184
Opened 2024-12-30 20:56 UTC by guberathome

Adresses #183.

Instead of checking  sizeof(ucell_t) as function call conditional compilation is used.
```
void WriteCellBigEndian( uint8_t *addr, ucell_t data )
...
	#if (LONG_MAX > 2147483647)  /* LONG_MAX from limits.h: values > 2^31-1 indicates 64bit ints */
...
```

LONG_MAX will be set to 2147483647 = (2^32-1) for 32 bit builds (and greater values for 64bit builds).
If I read the documentation correctly LONG_MAX is part of POSIX 1003.
**Please verify that this does not impair any target platform.**

Solution was tested (make clean all test) on Manjaro, FreeBSD and NetBSD for X86_64 architectures.

2024-12-31 20:53 UTC, philburk requested changes
Thanks for contributing.
I agree tht we should get rid of the earnings.

2024-12-31 20:53 UTC, philburk commented on csrc/pf_save.c
> +	#if (LONG_MAX > 2147483647)  /* LONG_MAX from limits.h: values > 2^31-1 indicates 64bit ints */
Thanks for the idea. We start conditional compilation in column 0.
And we can use PF_SIZEOF_CELL, which is used in multiple places for similar purposes.
So it should be safe.

```suggestion
#if (PF_SIZEOF_CELL == 8)
```

2024-12-31 20:53 UTC, philburk commented on csrc/pf_save.c
> +	#endif
Column 0.

```suggestion
#endif   /* PF_SIZEOF_CELL */
```

2024-12-31 23:21 UTC, guberathome commented
> Thanks for contributing. I agree tht we should get rid of the earnings.

Happy to help.
Changes looked good to me. 

Verified on NetBSD (i386) and MSYS2 (x86_64) that this works as intended.

2025-01-01 00:34 UTC, philburk approved these changes

2025-01-01 00:34 UTC, merged